networks:
  argendar_net:
    driver: bridge

services:
  prueba_frontend:
    build:
      context: ./prueba
      dockerfile: Dockerfile.dev
    container_name: argendar_prueba_frontend
    ports:
      - "5173:5173" # Usamos el mismo puerto que el frontend original
    volumes:
      - ./prueba:/app
      - /app/node_modules
    env_file:
      - ./prueba/.env
    networks:
      - argendar_net
